export interface Channels {
    id: number,
    name: string,
    username: string,
    topic: string,
    subscribersCount: number,
    averageReach: number,
    adPrice: number,
    repostsCount: number,
    commentsCount: number,
    description: string,
    status: 'published' | 'draft' | 'deleted',
    coverUrl: string,
    videoUrl: string,
    nextId?: number
}

export const channels : Channels[] = [
  {
    id: 1,
    name: 'Код на прокачку',
    username: 'codeboost',
    topic: 'Технологии и программирование',
    subscribersCount: 42800,
    averageReach: 12400,
    adPrice: 7500,
    repostsCount: 142,
    commentsCount: 56,
    description: 'Короткие разборы кода, новости из мира IT и полезные трюки для разработчиков каждый день.',
    status: 'published',
    coverUrl: 'http://localhost:9000/posttrace/cover1.jpg',
    videoUrl: 'http://localhost:9000/posttrace/video1.mp4',
    nextId: 2
  },
  {
    id: 2,
    name: 'Новости дня',
    username: 'dailynews',
    topic: 'Новости и медиа',
    subscribersCount: 124000,
    averageReach: 38900,
    adPrice: 15000,
    repostsCount: 892,
    commentsCount: 324,
    description: 'Самые важные новости за день, кратко и по делу без воды.',
    status: 'published',
    coverUrl: 'http://localhost:9000/posttrace/cover2.jpg',
    videoUrl: 'http://localhost:9000/posttrace/video2.mp4',
    nextId: 3
  },
  {
    id: 3,
    name: 'Мемная берлога',
    username: 'memeden',
    topic: 'Юмор и развлечения',
    subscribersCount: 27600,
    averageReach: 9200,
    adPrice: 3200,
    repostsCount: 412,
    commentsCount: 128,
    description: 'Свежие мемы каждый час, поднимаем настроение после пар.',
    status: 'published',
    coverUrl: 'http://localhost:9000/posttrace/cover3.jpg',
    videoUrl: 'http://localhost:9000/posttrace/video3.mp4',
    nextId: 4
  },
  {
    id: 4,
    name: 'Бизнес без галстука',
    username: 'biznogalstuk',
    topic: 'Бизнес и маркетинг',
    subscribersCount: 18700,
    averageReach: 6400,
    adPrice: 4800,
    repostsCount: 78,
    commentsCount: 34,
    description: 'Реальные кейсы малого бизнеса, разборы маркетинговых фишек и рабочие схемы заработка.',
    status: 'published',
    coverUrl: 'http://localhost:9000/posttrace/cover4.jpg',
    videoUrl: 'http://localhost:9000/posttrace/video4.mp4',
    nextId: 5
  },
  {
    id: 5,
    name: 'Путешествия из Химок',
    username: 'travelkhimki',
    topic: 'Путешествия',
    subscribersCount: 9400,
    averageReach: 3100,
    adPrice: 2100,
    repostsCount: 54,
    commentsCount: 19,
    description: 'Бюджетные путешествия из России, проверенные маршруты и лайфхаки в поездках.',
    status: 'published',
    coverUrl: 'http://localhost:9000/posttrace/cover5.jpg',
    videoUrl: 'http://localhost:9000/posttrace/video5.mp4',
    nextId: 1 // Замыкаем круг, после последнего открывается первый канал
  },
  // 1 черновик, отображается только на странице добавления
  {
    id: 6,
    name: 'Лекции МГТУ',
    username: 'bmstulect',
    topic: 'Образование',
    subscribersCount: 0,
    averageReach: 0,
    adPrice: 0,
    repostsCount: 0,
    commentsCount: 0,
    description: 'Конспекты лекций и разборы лабораторных работ для студентов Бауманки.',
    status: 'draft',
    coverUrl: 'http://localhost:9000/posttrace/cover6.jpg',
    videoUrl: 'http://localhost:9000/posttrace/video6.mp4',
  }
];
